language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE="luv"
matrix:
  include:
    - os: freebsd
      env: OCAML_VERSION=4.10
